---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# platforms:
#  - name: ubuntu-14.04
# specific to run on asus labby
platforms:
  - name: ub-14.04-i386
    driver:
      box: ub-14.04-i386
      box_url: https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-i386-vagrant-disk1.box

#  - name: windows-2012r2
#    transport:
#      name: winrm
#      port: 5985
#      username: vagrant
#      password: vagrant
#    driver_config:
#      box: windows2012r2
#      box_url: http://localhost/windows2012r2.box

suites:
  - name: default
    run_list:
      - recipe[sdinc-shinken::default]
    encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
    attributes:
      shinken:
        install_type: source
